<?php
/*
Copyright 2012 Andrew Hilts

This file is part of the webform email lookup module (a Drupal module).

Webform Email Lookup is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Webform Email Lookup is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

To review a copy of the GNU General Public License, see http://www.gnu.org/licenses/.
*/

/*
 * Implementation of hook_menu()
 */
function webform_submission_lookup_menu(){
  $items = array();
  $items['node/%webform_menu/lookup'] = array(
      'title' => t('Lookup'),
      'description' => t('Choose random result'),
      'page callback' => 'webform_submission_lookup_display',
      'page arguments' => array(1),
      'access arguments' => array('webform submission lookup'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 10,
    );
  return $items;
}

/**
 * Implements hook_perm().
 */
function webform_submission_lookup_perm() {
  return array('webform submission lookup');
}

/**
 * Implements hook_views_api().
 */
function webform_submission_lookup_views_api() {
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module', 'webform_submission_lookup') . '/views',
  );
}

function webform_submission_lookup_display($node){
  $nid = $node->nid;
  $output = drupal_get_form('webform_submission_lookup_form',$nid);
  if(isset($_GET['email_lookup'])){
    $email = $_GET['email_lookup'];
    if(!valid_email_address($email)){
      drupal_set_message('Please enter a properly-formed e-mail address','warning');
    }
    else{
      //Get email cid(s)
      $cids = webform_submission_lookup_get_cids($nid,"email");
      if(!$cids){
        return $output;
      }
      $submissions=array();
      $submissions = webform_submission_lookup_query($nid,$email,$cids);
      if(count($submissions) > 0){
        $output .= theme('webform_submission_lookup_table',$submissions);
      }
      else{
        drupal_set_message(t("No submissions found for that email"));
      }
    }
  }
  return $output;
}

function webform_submission_lookup_form(&$form_state,$nid){
  $form = array(
    'email' => array(
      '#title' => t('Email Address'),
      '#type' => 'textfield',
      '#size' => 30,
      '#maxlength' => 200,
      '#description' => t('Enter an email address to check if it is present in the webform submissions'),
    ),
    'submit' => array(
      '#type' => 'submit',
      '#default_value' => t('Lookup Address!'),
    )
  );
  $form['path'] = array(
    '#type' => 'hidden',
    '#default_value' => "node/$nid/lookup",
  );
  return $form;
}

function webform_submission_lookup_form_submit($form, &$form_state){

  $query = array(
    'email_lookup' => $form_state['values']['email'],
  );

  $form_state['redirect'] = array($form_state['values']['path'],$query);
}

function webform_submission_lookup_query($nid,$email,$cids){

  if(!valid_email_address($email)){
    drupal_set_message('Please enter a properly-formed e-mail address','warning');
    return FALSE;
  }

  $sql = "SELECT DISTINCT ws.sid sid, ws.is_draft, wsd.data, wsd.nid, ws.submitted FROM {webform_submissions} ws INNER JOIN {webform_submitted_data} wsd ON (ws.sid = wsd.sid) WHERE ws.nid = %d AND wsd.data = '%s' AND wsd.cid IN (".db_placeholders($cids).") ORDER BY ws.submitted DESC";

  $vars = array_merge(array($nid,$email),$cids);

  $result = db_query($sql,$vars);

  $submissions = array();
  while ( $row = db_fetch_object($result) ) {
    if ( $row->is_draft == 0 ) {
      $submissions[] = $row;
    }
  }
  return $submissions;
}

function webform_submission_lookup_get_cids($nid,$type){
  $sql = "SELECT DISTINCT cid FROM {webform_component} WHERE nid=%d AND type = '%s'";
  $result = db_query($sql,$nid,$type);
  $components = array();
  while ($row = db_fetch_object($result)) {
    $components[] = $row->cid;
  }
  if(!isset($components[0])){
    drupal_set_message("No $type component found for this node.",'error');
    return FALSE;
  }
  return $components;
}

function theme_webform_submission_lookup_table($submissions){

  $header = array(
    t('Email'),
    t('Submission Date'),
    t('Submission Link'),
  );
  foreach($submissions as $i => $s){
    $path = "node/$s->nid/submission/$s->sid";
    $rows [] = array(
      $s->data,
      date("F j, Y, g:i a",$s->submitted),
      l(t('View sid #').$s->sid,$path),
    );
  }
  return theme_table($header,$rows);
}

function webform_submission_lookup_theme(){
  $theme = array(
    'webform_submission_lookup_table' => array(
      'arguments' => array('submissions' => NULL),
    ),
  );
  return $theme;
}